language: java
jdk: oraclejdk7
env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  - sudo apt-get update -qq

  # Install base Android SDK:
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required SDK components:
  - '( while : ; do echo y; sleep 10 ; done ) | android update sdk --all --no-ui --force'

